// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGCkHFdBbRp6G9Vn5UB3DhdKmEjFjER5Q',
    appId: '1:473435461695:web:3c6cff342c04c48790408a',
    messagingSenderId: '473435461695',
    projectId: 'task-69bef',
    authDomain: 'task-69bef.firebaseapp.com',
    storageBucket: 'task-69bef.firebasestorage.app',
    measurementId: 'G-MYME068X9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbnU017EqH40rW8NvesnFRYsDYV2qnmrY',
    appId: '1:473435461695:android:a4ea23b32a06f12590408a',
    messagingSenderId: '473435461695',
    projectId: 'task-69bef',
    storageBucket: 'task-69bef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1StnOVeOB_j87a8zCC5gewVOMUFqzjM',
    appId: '1:473435461695:ios:47e5ce5d432b3f4790408a',
    messagingSenderId: '473435461695',
    projectId: 'task-69bef',
    storageBucket: 'task-69bef.firebasestorage.app',
    iosBundleId: 'com.example.guessit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1StnOVeOB_j87a8zCC5gewVOMUFqzjM',
    appId: '1:473435461695:ios:47e5ce5d432b3f4790408a',
    messagingSenderId: '473435461695',
    projectId: 'task-69bef',
    storageBucket: 'task-69bef.firebasestorage.app',
    iosBundleId: 'com.example.guessit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGCkHFdBbRp6G9Vn5UB3DhdKmEjFjER5Q',
    appId: '1:473435461695:web:573ee1d227dd298e90408a',
    messagingSenderId: '473435461695',
    projectId: 'task-69bef',
    authDomain: 'task-69bef.firebaseapp.com',
    storageBucket: 'task-69bef.firebasestorage.app',
    measurementId: 'G-XE8CNED3XM',
  );
}
